### ISSUE TITLE
Memory leak with Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by htr3n** [yvbbrjdr/i3lock-fancy-rapid#12]
There is no problem with `i3lock-fancy-rapid` in Ubuntu 18 LTS but in 20.04 LTS, got this error after unlocking the screen.

```
$ i3lock-fancy-rapid 5 3
...
~/build/i3lock-fancy-rapid master
=================================================================
==42054==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4864 byte(s) in 19 object(s) allocated from:
    #0 0x7f4fd4be2bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f4fd3e572f4  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x212f4)

Indirect leak of 1184 byte(s) in 37 object(s) allocated from:
    #0 0x7f4fd4be2dc6 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7f4fd3e5793c  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2193c)

Indirect leak of 341 byte(s) in 34 object(s) allocated from:
    #0 0x7f4fd4b6b3dd in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x963dd)
    #1 0x7f4fd3e56b64 in FcValueSave (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20b64)

SUMMARY: AddressSanitizer: 6389 byte(s) leaked in 90 allocation(s).
```

I built `i3lock-fancy-rapid` from source pulled from Github `master`.

Edited: Before `i3lock-fancy-rapid` worked with i3 normally but it's no longer working after upgrading to Ubuntu 20.04. Executed `i3lock-fancy-rapid` from command line like above, I got the error.

**Comment by htr3n** [comment]
Similar to this one: https://github.com/Raymo111/i3lock-color/issues/88

**Comment by htr3n** [comment]
Finally, upgrade i3lock (from github master) resolved the error. See: https://github.com/i3/i3lock/issues/167

**Comment by htr3n** [comment]
Related to this bug: https://github.com/i3/i3lock/issues/167

**Comment by Animeshz** [comment]
Seems like upstream has fixed it, is it fixed?
